export const ADD_API_REQUEST = "ADD_API_REQUEST"

export const ADD_API_SUCCESS =  "ADD_API_SUCCESS"

export const ADD_API_FAILS =  "ADD_API_FAILS"

export const GET_API_REQUEST = "GET_API_REQUEST" 

export const GET_API_SUCCESS = "GET_API_SUCCESS" 

export const GET_API_FAILS = "GET_API_FAILS" 

export const GET_ALL_API_REQUEST = "GET_ALL_API_REQUEST"

export const GET_ALL_API_SUCCESS = "GET_ALL_API_SUCCESS"

export const GET_ALL_API_FAILS = "GET_ALL_API_FAILS" 

export const GET_USER_API_REQUEST = "GET_USER_API_REQUEST"

export const GET_USER_API_SUCCESS = "GET_USER_API_SUCCESS"

export const GET_USER_API_FAILS = "GET_USER_API_FAILS"

export const API_KEY_REQUEST = "API_KEY_REQUEST"

export const API_KEY_SUCCESS = "API_KEY_SUCCESS"

export const API_KEY_FAILS = "API_KEY_FAILS"